// Generated by CoffeeScript 2.0.3
(function() {
  'use strict';
  var CND, XTerm, alert, badge, blessed, body, copy_merge, counter, debug, every, fmanager, help, info, items, line_count, ref, rpr, screen, set_status, settings, top_screen, urge, warn, whisper, write_to_screen_one, xterm;

  /* https://ponyfoo.com/articles/understanding-javascript-async-await */
  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'YAU/DEMO-2';

  debug = CND.get_logger('debug', badge);

  alert = CND.get_logger('alert', badge);

  whisper = CND.get_logger('whisper', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  info = CND.get_logger('info', badge);

  //...........................................................................................................
  copy_merge = require('merge-options');

  blessed = require('blessed');

  XTerm = require('blessed-xterm');

  every = function(dts, f) {
    return setInterval(f, dts * 1000);
  };

  //-----------------------------------------------------------------------------------------------------------
  line_count = 20;

  //-----------------------------------------------------------------------------------------------------------
  settings = {
    //.........................................................................................................
    '*': {
      smartCSR: true,
      // log:                  process.env.HOME + '/blessed-terminal.log'
      fullUnicode: true,
      dockBorders: true,
      ignoreDockContrast: true,
      autoPadding: false,
      mouse: true
    },
    //.........................................................................................................
    base: {
      _extends: '*',
      top: 10,
      left: 20,
      width: '50%',
      height: '50%',
      label: ' {bold}{cyan-fg} LABEL HERE {/cyan-fg}{/bold} {#0088ff-fg}(Drag Me){/#0088ff-fg} ',
      draggable: true,
      border: 'line',
      tags: true,
      style: {
        fg: 'default',
        bg: 'default',
        border: {
          fg: 'default'
        },
        focus: {
          border: {
            fg: 'cyan'
          }
        },
        scrolling: {
          border: {
            fg: 'red'
          }
        }
      }
    },
    // cursor:        { color: 'red', }
    //.........................................................................................................
    screen: {
      _extends: '*',
      log: '/tmp/blessed-terminal.log',
      _title: 'robotron'
    },
    //.........................................................................................................
    screen_one: {
      _extends: 'base',
      top: 10,
      left: 20,
      width: '50%',
      height: line_count,
      label: ' {bold}{cyan-fg}ANSI Art{/cyan-fg}{/bold} {#0088ff-fg}(Drag Me){/#0088ff-fg} '
    },
    //.........................................................................................................
    top_screen: {
      _extends: 'base',
      top: 3,
      left: 80,
      width: '50%',
      height: 10,
      label: ' {bold}{cyan-fg}top{/cyan-fg}{/bold} {#0088ff-fg}(Drag Me){/#0088ff-fg} ',
      // handler:        ->
      style: {
        fg: 'default',
        bg: 'yellow',
        focus: {
          border: {
            fg: 'green'
          }
        }
      }
    },
    //.........................................................................................................
    fmanager: {
      _extends: 'base',
      // // parent: screen
      border: 'line',
      top: 0,
      left: 80,
      width: '25%',
      height: '50%',
      draggable: true,
      mouse: true,
      cwd: __dirname
    },
    //.........................................................................................................
    terminals: {
      _extends: 'base',
      shell: process.env.SHELL || 'sh',
      args: [],
      env: process.env,
      cwd: process.cwd(),
      cursorType: 'block',
      scrollback: 1000,
      label: "terminal"
    },
    //.........................................................................................................
    xterm: {
      _extends: 'terminals',
      shell: 'top',
      args: ['-d', '0.1'],
      left: 0,
      top: 0,
      width: function(screen) {
        return Math.floor(screen.width / 2);
      },
      height: function(screen) {
        return screen.height;
      },
      label: "Sample XTerm #1"
    }
  };

  //-----------------------------------------------------------------------------------------------------------
  this.resolve_dependencies = function(settings, key) {
    return this._resolve_dependencies(settings, key, []);
  };

  //-----------------------------------------------------------------------------------------------------------
  this._resolve_dependencies = function(settings, key, R) {
    var entry, sub_key;
    entry = settings[key];
    if (entry == null) {
      throw new Error(`unknown settings key ${rpr(key)}`);
    }
    R.unshift(key);
    if ((sub_key = entry._extends) != null) {
      return this._resolve_dependencies(settings, sub_key, R);
    }
    return R;
  };

  //-----------------------------------------------------------------------------------------------------------
  this._list_settings_from_key = function(settings, key) {
    var k;
    return (function() {
      var j, len, ref, results;
      ref = this.resolve_dependencies(settings, key);
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        k = ref[j];
        results.push(settings[k]);
      }
      return results;
    }).call(this);
  };

  //-----------------------------------------------------------------------------------------------------------
  this.settings_from_key = function(parent, settings, key) {
    var R, arity, f, j, k, len, ref;
    switch (arity = arguments.length) {
      case 2:
        [parent, settings, key] = [null, parent, settings];
        break;
      case 3:
        null;
        break;
      default:
        throw new Error(`expected 2 or 3 arguments, got ${arity}`);
    }
    //.........................................................................................................
    R = copy_merge(...(this._list_settings_from_key(settings, key)));
    ref = ['left', 'top', 'width', 'height'];
    for (j = 0, len = ref.length; j < len; j++) {
      k = ref[j];
      if (!CND.isa_function((f = R[k]))) {
        continue;
      }
      R[k] = f(parent);
    }
    //.........................................................................................................
    return R;
  };

  //-----------------------------------------------------------------------------------------------------------
  screen = blessed.screen(this.settings_from_key(settings, 'screen'));

  screen.title = (ref = settings.screen._title) != null ? ref : 'kannwas';

  screen.key(['escape', 'C-q'], function(chr, key) {
    return process.exit(0);
  });

  //...........................................................................................................
  body = blessed.box(this.settings_from_key(screen, settings, 'screen_one'));

  fmanager = blessed.filemanager(this.settings_from_key(screen, settings, 'fmanager'));

  top_screen = blessed.box(this.settings_from_key(screen, settings, 'top_screen'));

  xterm = new XTerm(this.settings_from_key(screen, settings, 'xterm'));

  // #...........................................................................................................
  // terminal.pty.on 'data', ( data ) ->
  //   screen.log JSON.stringify data

  //...........................................................................................................
  screen.append(body);

  screen.append(fmanager);

  screen.append(top_screen);

  screen.append(xterm);

  // screen.append terminal

  // terminal.focus()
  screen.render();

  items = [];

  counter = 1;

  write_to_screen_one = function(text) {
    var i, j, ref1;
    items.push(text);
    if (items.length > line_count + 1) {
      items.shift();
    }
    for (i = j = 1, ref1 = line_count; j < ref1; i = j += +1) {
      body.setLine(i, items[i]);
    }
    return screen.render();
  };

  set_status = function(text) {
    body.setLine(0, text);
    return screen.render();
  };

  every(0.01, function() {
    set_status(new Date().toISOString());
    counter += +1;
    return write_to_screen_one(`Line number: ${counter}`);
  });

}).call(this);

//# sourceMappingURL=main.js.map
